FROM ghcr.io/puppeteer/puppeteer:23.0.0

# Roda como root (Render gosta assim pra não dar permissão)
USER root

# Configs essenciais
ENV DISPLAY=:99 \
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY . .

# Roda com xvfb (já vem na imagem oficial)
CMD ["xvfb-run", "--server-args=-screen 0 1280x800x24", "--auto-servernum", "node", "server.js"]
